### ISSUE TITLE
Exporting query no longer works

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#105]
Whenever, I export a query, I receive a dialog that says I don't have permission to download, followed by the regular export dialog. However, the export never reaches my inbox. 

This is the query I used (which passed the query syntax): (+"Coca Cola" -("Fanta" "Sprite") +paper_dc_title:"Limburgsch Dagblad")

This occurs on the surfsara domain.

**Comment by JosedeKruif** [comment]
Did you logout before the download arrived?

**Comment by mhkuu** [comment]
I think the permissions on group level were not set correctly; I just fixed that (hopefully), can you check again?

**Comment by melvinwevers** [comment]
@mhkuu still the same. After refreshing the cache. 

@JosedeKruif I know about the logout, and if I did I would have mentioned it, as this is not regular user behavior. 2), No I did not check my spambox, since these emails never arrive in my spambox. And the changed behavior is a pop-up dialog 3) If you really want to know, because this is very off-topic. I am well aware of the fact that you don't need brackets here, but for reasons of legibility I include them here, since the OR disappeared. 

So, instead of repeating the discussion on query syntax, let's just work constructively and try to fix this issue. I am not attacking you guys, I'm merely notifying you of stuff that's not working.

**Comment by JosedeKruif** [comment]
I have sent you the file you want. As you will see, the UU mailsystem marks it as SPAM. I was just curious if that was the problem. I wrote the query this way: +"Coca Cola" -Fanta -Sprite +paper_dc_title:Limburgsch Dagblad. I got the same number of hits you got.

**Comment by melvinwevers** [comment]
@JosedeKruif. Thanks for the file. I do need a couple more, unfortunately. 
Re: the syntax. I know that you can write it in other ways, I chose to do it in this way, as I said to make it more legible. I also made somewhat more complicated queries and then the parentheses make sense, in order to guide the reader, I try to keep the syntax somewhat consistent (even though sometimes redundant)

**Comment by JosedeKruif** [comment]
Well, give me the queries and I will download the files and send them to you. If we do not get the problem solved today, at least you will have your files.

**Comment by melvinwevers** [comment]
Thanks, I appreciate this. 
For now, these would be great:

+"Coca Cola" -("Fanta" "Sprite") +paper_dc_title:"De Waarheid" 
+"Coca Cola" -("Fanta" "Sprite") +paper_dc_title:"Het vrĳe volk : democratisch-socialistisch dagblad"
+"Coca Cola" -("Fanta" "Sprite") +paper_dc_title:"De Telegraaf" 
+"Coca Cola" -("Fanta" "Sprite") +paper_dc_title:"Limburgsch Dagblad"

btw these should only include articles  from 1928 to 1989

**Comment by melvinwevers** [comment]
Oh one more thing. The email are sent to my gmail domain. Maybe that is causing the problem, I think I read something about restricting use to UU-users.

**Comment by JosedeKruif** [comment]
The gmail could be in issue, I guess. In Django you are registrated with you gmailaddress (I just had a look I will change this information in Basecamp). Because of copyright problems users who download must be in the UU domain but I am not sure how this is implemented.

**Comment by mhkuu** [comment]
It should work now; permissions on group level were not set correctly (by me).
